version: '3'

tasks:
  ci:fast:
    cmds:
      - pnpm install --frozen-lockfile
      - pnpm check:naming
      - pnpm lint
      - pnpm build
      - pnpm test

  ci:
    cmds:
      - task: ci:fast
