/**
 * Report Generator
 * Generates Markdown or JSON reports from CompareDesignResult
 */

import type { CompareDesignResult } from "@figdiff/shared";

/**
 * Generate a Markdown diff report
 */
export function generateMarkdownReport(result: CompareDesignResult): string {
  const lines: string[] = [];

  lines.push("# FigDiff Comparison Report");
  lines.push("");
  lines.push(`**Comparison ID:** ${result.comparisonId}`);
  lines.push(`**Match Rate:** ${result.matchRate}%`);
  lines.push(
    `**Diff Pixels:** ${result.diffPixelCount.toLocaleString()} / ${result.totalPixelCount.toLocaleString()}`,
  );
  lines.push("");

  if (result.diffRegions.length === 0) {
    lines.push("No differences found. Design and implementation match perfectly.");
  } else {
    lines.push(`## Diff Regions (${result.diffRegions.length})`);
    lines.push("");

    for (const region of result.diffRegions) {
      lines.push(`### Region ${region.id + 1}`);
      lines.push(`- **Position:** (${region.bounds.x}, ${region.bounds.y})`);
      lines.push(`- **Size:** ${region.bounds.width}x${region.bounds.height}px`);
      lines.push(`- **Diff Pixels:** ${region.diffPixelCount.toLocaleString()}`);

      if (region.nearbyNodeIds.length > 0) {
        lines.push(`- **Nearby Figma Nodes:**`);
        for (let i = 0; i < region.nearbyNodeIds.length; i++) {
          lines.push(`  - ${region.nearbyNodeNames[i]} (\`${region.nearbyNodeIds[i]}\`)`);
        }
      }

      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`*Generated by FigDiff at ${new Date().toISOString()}*`);

  return lines.join("\n");
}

/**
 * Generate a JSON report (structured data)
 */
export function generateJsonReport(result: CompareDesignResult): string {
  const { diffImageBase64: _, ...withoutImage } = result;
  return JSON.stringify(withoutImage, null, 2);
}
