/**
 * Report Generator
 * Generates Markdown or JSON reports from CompareDesignResult
 */

import type { CompareDesignResult } from "@figdiff/shared";

/**
 * Generate a Markdown diff report
 */
export function generateMarkdownReport(result: CompareDesignResult): string {
  const lines: string[] = [];
  const remainingIssues = result.remainingIssues ?? result.diffRegions.length;

  lines.push("# FigDiff Comparison Report");
  lines.push("");
  lines.push(`**Comparison ID:** ${result.comparisonId}`);
  lines.push(`**Match Rate:** ${result.matchRate}%`);
  lines.push(
    `**Diff Pixels:** ${result.diffPixelCount.toLocaleString()} / ${result.totalPixelCount.toLocaleString()}`,
  );
  lines.push(`**Remaining Issues:** ${remainingIssues}`);
  lines.push(
    `**Suggested Next Action:** ${result.nextAction ?? "Inspect critical diff regions and apply targeted CSS fixes."}`,
  );
  lines.push("");

  appendComplianceBenchmark(lines, result, remainingIssues);
  appendTypedDiffEvidence(lines, result.diffReport);

  if (result.diffRegions.length === 0) {
    lines.push("No differences found. Design and implementation match perfectly.");
  } else {
    lines.push(`## Diff Regions (${result.diffRegions.length})`);
    lines.push("");

    for (const region of result.diffRegions) {
      lines.push(`### Region ${region.id + 1}`);
      lines.push(`- **Position:** (${region.bounds.x}, ${region.bounds.y})`);
      lines.push(`- **Size:** ${region.bounds.width}x${region.bounds.height}px`);
      lines.push(`- **Diff Pixels:** ${region.diffPixelCount.toLocaleString()}`);

      if (region.nearbyNodeIds.length > 0) {
        lines.push(`- **Nearby Figma Nodes:**`);
        for (let i = 0; i < region.nearbyNodeIds.length; i++) {
          lines.push(`  - ${region.nearbyNodeNames[i]} (\`${region.nearbyNodeIds[i]}\`)`);
        }
      }

      lines.push("");
    }
  }

  lines.push("---");
  if (result.diffImagePath) {
    lines.push(`Evidence image: ${result.diffImagePath}`);
  }
  lines.push(`*Generated by FigDiff at ${new Date().toISOString()}*`);

  return lines.join("\n");
}

function appendComplianceBenchmark(
  lines: string[],
  result: CompareDesignResult,
  remainingIssues: number,
): void {
  const completionCriteria = result.completionCriteria;
  const diffReport = result.diffReport;

  lines.push("## Compliance Benchmark Snapshot");
  lines.push("");
  lines.push("| Check | Target | Current | Status |");
  lines.push("| --- | --- | --- | --- |");
  // 最終 status を出さないと、整合ゲートで人間レビューへ回った比較でも
  // この表だけを見た読み手には PASS に見えてしまう。
  lines.push(`| Final Status | PASS | ${result.status} | ${result.status} |`);
  if (completionCriteria?.consistencyReview) {
    const consistency = completionCriteria.consistencyReview;
    lines.push(
      `| Consistency Review | <= ${consistency.required} | ${consistency.current} | ${consistency.status} |`,
    );
  }
  lines.push(
    `| Match Rate | ${completionCriteria?.matchRate.required ?? "n/a"} | ${completionCriteria?.matchRate.current ?? result.matchRate} | ${completionCriteria?.matchRate.status ?? "n/a"} |`,
  );
  lines.push(
    `| Diff Pixel Count | ${completionCriteria?.diffPixelCount.required ?? "n/a"} | ${completionCriteria?.diffPixelCount.current ?? result.diffPixelCount} | ${completionCriteria?.diffPixelCount.status ?? "n/a"} |`,
  );
  lines.push(
    `| Remaining Issues | ${completionCriteria?.remainingIssues.required ?? "n/a"} | ${completionCriteria?.remainingIssues.current ?? remainingIssues} | ${completionCriteria?.remainingIssues.status ?? "n/a"} |`,
  );

  if (diffReport) {
    // 構造判定の行に自前の PASS/FAIL を書くと、最終 status が UNCERTAIN でも
    // この行だけ PASS と主張してしまう。判定済みの status をそのまま使う。
    const structuralStatus =
      completionCriteria?.structuralReview.status ??
      (diffReport.aggregateVerdict === "pass" ? "PASS" : "FAIL");
    lines.push(`| Diff Verdict | pass | ${diffReport.aggregateVerdict} | ${structuralStatus} |`);
  }

  lines.push("");
}

function appendTypedDiffEvidence(
  lines: string[],
  diffReport: CompareDesignResult["diffReport"],
): void {
  if (!diffReport) {
    return;
  }

  const criticalIssueCount = diffReport.issues.filter(
    (issue) => issue.severity === "critical",
  ).length;
  lines.push("## Evidence for Figma Compliance");
  lines.push("");
  lines.push(`- Aggregate Verdict: **${diffReport.aggregateVerdict}**`);
  lines.push(`- Critical Issues: **${criticalIssueCount}**`);
  lines.push(`- Total Typed Issues: **${diffReport.issues.length}**`);
  lines.push(`- Rationale: ${diffReport.rationale}`);
  lines.push("");
  if (diffReport.issues.length > 0) {
    lines.push("### Typed Issues (Expected vs Actual)");
    lines.push("");
    for (const [index, issue] of diffReport.issues.entries()) {
      lines.push(
        `${index + 1}. \`${issue.kind}\` (${issue.severity}) signal=\`${issue.evidence.signal}\``,
      );
      lines.push(`   - Expected: \`${String(issue.evidence.expected)}\``);
      lines.push(`   - Actual: \`${String(issue.evidence.actual)}\``);
      if (
        issue.evidence.figmaFileKey ||
        issue.evidence.figmaNodeId ||
        issue.evidence.figmaPageName
      ) {
        lines.push(
          `   - Provenance: fileKey=\`${issue.evidence.figmaFileKey ?? "n/a"}\`, nodeId=\`${issue.evidence.figmaNodeId ?? "n/a"}\`, page=\`${issue.evidence.figmaPageName ?? "n/a"}\``,
        );
      }
    }
    lines.push("");
  }
}

/**
 * Generate a JSON report (structured data)
 */
export function generateJsonReport(result: CompareDesignResult): string {
  const { diffImageBase64: _, ...withoutImage } = result;
  return JSON.stringify(withoutImage, null, 2);
}
